### ISSUE TITLE
CSS问题-元素竖向的百分比设定是相对于容器的高度吗？

### ISSUE THREAD

**Issue by Seasonley** [FEGuideTeam/FEGuide#7]
难道不是高度？？

**Comment by nanhupatar** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/height

**Comment by nanhupatar** [comment]
@Seasonley

**Comment by Seasonley** [comment]
@nanhupatar 我没理解题目意思。我理解的是这个：

> **\<percentage\>**
> 将高度定义为相对包含块高度的百分比。
>https://developer.mozilla.org/zh-CN/docs/Web/CSS/height#%E5%80%BC
